### PR TITLE
Package upgrade

### PR DESCRIPTION
**Pull request by Dananji**
This PR upgrades outdated yarn dependencies and fixes broken code due to the upgrades. This is a continuation of work from issue #56.

### CODE REVIEW

**Comment by Dananji** [comment]
@adamjarling Initially the CircleCI build failed when it was trying to install dependencies with `yarn install --frozen-lockfile` command. This happened when I ran the command locally as well. Later I found out that the reason for this was duplicating packages in both `dependencies` and `resolutions` in package.json file. The resolutions were added as a result of security fixes suggested by Dependabot to force to pull specific (latest) version of some packages in `yarn.lock` file.
Have you experienced this issue before?

**Comment by adamjarling** [comment]
Hmm, I've only really used resolutions for local component import testing.  I'd say in general, let's just get through this current code base ignoring any dependabot extra suggestions, for now, and get this environment re-factored to use `https://github.com/samvera-labs/starter-react-component-npm` sooner than later?

**Review by adamjarling — APPROVED** [review]
Looks good!

**Comment by Dananji** [comment]
Yeah sounds good :100:

**Pull request merged**
